# Generated by Django 6.0 on 2026-01-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('VERIFIED', 'Verified'), ('ACTIVATED', 'Activated'), ('FAILED', 'Failed')], db_index=True, default='CREATED', max_length=20),
        ),
    ]
