# Generated by Django 6.0 on 2026-01-27 16:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'playlists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('visibility', models.CharField(choices=[('GLOBAL', 'Global'), ('TENANT', 'Tenant')], default='TENANT', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(blank=True, max_length=255)),
                ('duration', models.PositiveSmallIntegerField()),
                ('release_year', models.PositiveSmallIntegerField()),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='music.genre')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'songs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SongRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('song_title', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('album_name', models.CharField(blank=True, max_length=255)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FULFILLED', 'Fulfilled')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('fulfilled_song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_requests', to='music.song')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_song_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_requests', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Song Request',
                'verbose_name_plural': 'Song Requests',
                'db_table': 'song_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantSong',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_links', to='music.song')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_songs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Song Link',
                'verbose_name_plural': 'Tenant Song Links',
                'db_table': 'tenant_songs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='music.playlist')),
                ('tenant_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='music.tenantsong')),
            ],
            options={
                'db_table': 'playlist_songs',
            },
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'name'), name='unique_playlist_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['tenant', 'visibility'], name='songs_tenant__a7c527_idx'),
        ),
        migrations.AddIndex(
            model_name='songrequest',
            index=models.Index(fields=['tenant', 'status'], name='song_reques_tenant__adfebc_idx'),
        ),
        migrations.AddIndex(
            model_name='songrequest',
            index=models.Index(fields=['requester', 'status'], name='song_reques_request_b9237d_idx'),
        ),
        migrations.AddIndex(
            model_name='songrequest',
            index=models.Index(fields=['tenant', 'created_at'], name='song_reques_tenant__79a7be_idx'),
        ),
        migrations.AddConstraint(
            model_name='songrequest',
            constraint=models.UniqueConstraint(fields=('song_title', 'tenant'), name='unique_song_request_per_user_tenant'),
        ),
        migrations.AddIndex(
            model_name='tenantsong',
            index=models.Index(fields=['tenant', 'song'], name='tenant_song_tenant__783db2_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantsong',
            index=models.Index(fields=['tenant', 'is_active'], name='tenant_song_tenant__1811e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantsong',
            constraint=models.UniqueConstraint(fields=('tenant', 'song'), name='unique_song_per_tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistsong',
            unique_together={('playlist', 'tenant_song')},
        ),
    ]
