# Generated by Django 6.0 on 2026-01-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='visibility',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('TENANT', 'Tenant')], default='GLOBAL', max_length=20),
        ),
    ]
